// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnIZ3Ixwo4o43DGSfjU15xYq_R949oyjI',
    appId: '1:991213914954:web:822bd2312a516682d5cfb3',
    messagingSenderId: '991213914954',
    projectId: 'faresproject-2261d',
    authDomain: 'faresproject-2261d.firebaseapp.com',
    storageBucket: 'faresproject-2261d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt3vmDGe0sVKDdlk6tjdj6mTJJX_poNoQ',
    appId: '1:991213914954:android:a02fb143684c0427d5cfb3',
    messagingSenderId: '991213914954',
    projectId: 'faresproject-2261d',
    storageBucket: 'faresproject-2261d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbpvJsfR6lZu-Lg-5aeYLfPcKIhRcFnw0',
    appId: '1:991213914954:ios:ecf8305a1d8b9191d5cfb3',
    messagingSenderId: '991213914954',
    projectId: 'faresproject-2261d',
    storageBucket: 'faresproject-2261d.appspot.com',
    iosBundleId: 'com.example.faresProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbpvJsfR6lZu-Lg-5aeYLfPcKIhRcFnw0',
    appId: '1:991213914954:ios:8f16d4205bf72b3fd5cfb3',
    messagingSenderId: '991213914954',
    projectId: 'faresproject-2261d',
    storageBucket: 'faresproject-2261d.appspot.com',
    iosBundleId: 'com.example.faresProject.RunnerTests',
  );
}
